// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vega.Classes;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MainDatabaseContext))]
    [Migration("20240118140153_i")]
    partial class i
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Vega.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "http://author1.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(3),
                            Description = "Blog Description 1",
                            Text = "Blog Text 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "http://author2.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(107),
                            Description = "Blog Description 2",
                            Text = "Blog Text 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "http://author3.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(124),
                            Description = "Blog Description 3",
                            Text = "Blog Text 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "http://author4.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(197),
                            Description = "Blog Description 4",
                            Text = "Blog Text 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "http://author5.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(213),
                            Description = "Blog Description 5",
                            Text = "Blog Text 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "http://author6.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(233),
                            Description = "Blog Description 6",
                            Text = "Blog Text 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "http://author7.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(248),
                            Description = "Blog Description 7",
                            Text = "Blog Text 7"
                        },
                        new
                        {
                            Id = 8,
                            Author = "http://author8.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(263),
                            Description = "Blog Description 8",
                            Text = "Blog Text 8"
                        },
                        new
                        {
                            Id = 9,
                            Author = "http://author9.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(277),
                            Description = "Blog Description 9",
                            Text = "Blog Text 9"
                        },
                        new
                        {
                            Id = 10,
                            Author = "http://author10.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(293),
                            Description = "Blog Description 10",
                            Text = "Blog Text 10"
                        },
                        new
                        {
                            Id = 11,
                            Author = "http://author11.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(311),
                            Description = "Blog Description 11",
                            Text = "Blog Text 11"
                        },
                        new
                        {
                            Id = 12,
                            Author = "http://author12.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(325),
                            Description = "Blog Description 12",
                            Text = "Blog Text 12"
                        },
                        new
                        {
                            Id = 13,
                            Author = "http://author13.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(340),
                            Description = "Blog Description 13",
                            Text = "Blog Text 13"
                        },
                        new
                        {
                            Id = 14,
                            Author = "http://author14.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(354),
                            Description = "Blog Description 14",
                            Text = "Blog Text 14"
                        },
                        new
                        {
                            Id = 15,
                            Author = "http://author15.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(368),
                            Description = "Blog Description 15",
                            Text = "Blog Text 15"
                        },
                        new
                        {
                            Id = 16,
                            Author = "http://author16.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(383),
                            Description = "Blog Description 16",
                            Text = "Blog Text 16"
                        },
                        new
                        {
                            Id = 17,
                            Author = "http://author17.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(398),
                            Description = "Blog Description 17",
                            Text = "Blog Text 17"
                        },
                        new
                        {
                            Id = 18,
                            Author = "http://author18.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(412),
                            Description = "Blog Description 18",
                            Text = "Blog Text 18"
                        },
                        new
                        {
                            Id = 19,
                            Author = "http://author19.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(427),
                            Description = "Blog Description 19",
                            Text = "Blog Text 19"
                        },
                        new
                        {
                            Id = 20,
                            Author = "http://author20.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(442),
                            Description = "Blog Description 20",
                            Text = "Blog Text 20"
                        },
                        new
                        {
                            Id = 21,
                            Author = "http://author21.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(509),
                            Description = "Blog Description 21",
                            Text = "Blog Text 21"
                        },
                        new
                        {
                            Id = 22,
                            Author = "http://author22.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(525),
                            Description = "Blog Description 22",
                            Text = "Blog Text 22"
                        },
                        new
                        {
                            Id = 23,
                            Author = "http://author23.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(539),
                            Description = "Blog Description 23",
                            Text = "Blog Text 23"
                        },
                        new
                        {
                            Id = 24,
                            Author = "http://author24.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(554),
                            Description = "Blog Description 24",
                            Text = "Blog Text 24"
                        },
                        new
                        {
                            Id = 25,
                            Author = "http://author25.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(568),
                            Description = "Blog Description 25",
                            Text = "Blog Text 25"
                        },
                        new
                        {
                            Id = 26,
                            Author = "http://author26.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(583),
                            Description = "Blog Description 26",
                            Text = "Blog Text 26"
                        },
                        new
                        {
                            Id = 27,
                            Author = "http://author27.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(597),
                            Description = "Blog Description 27",
                            Text = "Blog Text 27"
                        },
                        new
                        {
                            Id = 28,
                            Author = "http://author28.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(612),
                            Description = "Blog Description 28",
                            Text = "Blog Text 28"
                        },
                        new
                        {
                            Id = 29,
                            Author = "http://author29.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(627),
                            Description = "Blog Description 29",
                            Text = "Blog Text 29"
                        },
                        new
                        {
                            Id = 30,
                            Author = "http://author30.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(641),
                            Description = "Blog Description 30",
                            Text = "Blog Text 30"
                        },
                        new
                        {
                            Id = 31,
                            Author = "http://author31.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(655),
                            Description = "Blog Description 31",
                            Text = "Blog Text 31"
                        },
                        new
                        {
                            Id = 32,
                            Author = "http://author32.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(669),
                            Description = "Blog Description 32",
                            Text = "Blog Text 32"
                        },
                        new
                        {
                            Id = 33,
                            Author = "http://author33.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(682),
                            Description = "Blog Description 33",
                            Text = "Blog Text 33"
                        },
                        new
                        {
                            Id = 34,
                            Author = "http://author34.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(697),
                            Description = "Blog Description 34",
                            Text = "Blog Text 34"
                        },
                        new
                        {
                            Id = 35,
                            Author = "http://author35.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(712),
                            Description = "Blog Description 35",
                            Text = "Blog Text 35"
                        },
                        new
                        {
                            Id = 36,
                            Author = "http://author36.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(726),
                            Description = "Blog Description 36",
                            Text = "Blog Text 36"
                        },
                        new
                        {
                            Id = 37,
                            Author = "http://author37.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(740),
                            Description = "Blog Description 37",
                            Text = "Blog Text 37"
                        },
                        new
                        {
                            Id = 38,
                            Author = "http://author38.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(911),
                            Description = "Blog Description 38",
                            Text = "Blog Text 38"
                        },
                        new
                        {
                            Id = 39,
                            Author = "http://author39.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(927),
                            Description = "Blog Description 39",
                            Text = "Blog Text 39"
                        },
                        new
                        {
                            Id = 40,
                            Author = "http://author40.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(942),
                            Description = "Blog Description 40",
                            Text = "Blog Text 40"
                        },
                        new
                        {
                            Id = 41,
                            Author = "http://author41.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(956),
                            Description = "Blog Description 41",
                            Text = "Blog Text 41"
                        },
                        new
                        {
                            Id = 42,
                            Author = "http://author42.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(970),
                            Description = "Blog Description 42",
                            Text = "Blog Text 42"
                        },
                        new
                        {
                            Id = 43,
                            Author = "http://author43.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(984),
                            Description = "Blog Description 43",
                            Text = "Blog Text 43"
                        },
                        new
                        {
                            Id = 44,
                            Author = "http://author44.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(998),
                            Description = "Blog Description 44",
                            Text = "Blog Text 44"
                        },
                        new
                        {
                            Id = 45,
                            Author = "http://author45.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1012),
                            Description = "Blog Description 45",
                            Text = "Blog Text 45"
                        },
                        new
                        {
                            Id = 46,
                            Author = "http://author46.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1027),
                            Description = "Blog Description 46",
                            Text = "Blog Text 46"
                        },
                        new
                        {
                            Id = 47,
                            Author = "http://author47.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1041),
                            Description = "Blog Description 47",
                            Text = "Blog Text 47"
                        },
                        new
                        {
                            Id = 48,
                            Author = "http://author48.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1055),
                            Description = "Blog Description 48",
                            Text = "Blog Text 48"
                        },
                        new
                        {
                            Id = 49,
                            Author = "http://author49.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1069),
                            Description = "Blog Description 49",
                            Text = "Blog Text 49"
                        },
                        new
                        {
                            Id = 50,
                            Author = "http://author50.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1084),
                            Description = "Blog Description 50",
                            Text = "Blog Text 50"
                        },
                        new
                        {
                            Id = 51,
                            Author = "http://author51.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1097),
                            Description = "Blog Description 51",
                            Text = "Blog Text 51"
                        },
                        new
                        {
                            Id = 52,
                            Author = "http://author52.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1110),
                            Description = "Blog Description 52",
                            Text = "Blog Text 52"
                        },
                        new
                        {
                            Id = 53,
                            Author = "http://author53.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1125),
                            Description = "Blog Description 53",
                            Text = "Blog Text 53"
                        },
                        new
                        {
                            Id = 54,
                            Author = "http://author54.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1140),
                            Description = "Blog Description 54",
                            Text = "Blog Text 54"
                        },
                        new
                        {
                            Id = 55,
                            Author = "http://author55.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1153),
                            Description = "Blog Description 55",
                            Text = "Blog Text 55"
                        },
                        new
                        {
                            Id = 56,
                            Author = "http://author56.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1223),
                            Description = "Blog Description 56",
                            Text = "Blog Text 56"
                        },
                        new
                        {
                            Id = 57,
                            Author = "http://author57.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1237),
                            Description = "Blog Description 57",
                            Text = "Blog Text 57"
                        },
                        new
                        {
                            Id = 58,
                            Author = "http://author58.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1251),
                            Description = "Blog Description 58",
                            Text = "Blog Text 58"
                        },
                        new
                        {
                            Id = 59,
                            Author = "http://author59.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1265),
                            Description = "Blog Description 59",
                            Text = "Blog Text 59"
                        },
                        new
                        {
                            Id = 60,
                            Author = "http://author60.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1279),
                            Description = "Blog Description 60",
                            Text = "Blog Text 60"
                        },
                        new
                        {
                            Id = 61,
                            Author = "http://author61.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1293),
                            Description = "Blog Description 61",
                            Text = "Blog Text 61"
                        },
                        new
                        {
                            Id = 62,
                            Author = "http://author62.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1308),
                            Description = "Blog Description 62",
                            Text = "Blog Text 62"
                        },
                        new
                        {
                            Id = 63,
                            Author = "http://author63.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1321),
                            Description = "Blog Description 63",
                            Text = "Blog Text 63"
                        },
                        new
                        {
                            Id = 64,
                            Author = "http://author64.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1335),
                            Description = "Blog Description 64",
                            Text = "Blog Text 64"
                        },
                        new
                        {
                            Id = 65,
                            Author = "http://author65.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1349),
                            Description = "Blog Description 65",
                            Text = "Blog Text 65"
                        },
                        new
                        {
                            Id = 66,
                            Author = "http://author66.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1367),
                            Description = "Blog Description 66",
                            Text = "Blog Text 66"
                        },
                        new
                        {
                            Id = 67,
                            Author = "http://author67.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1381),
                            Description = "Blog Description 67",
                            Text = "Blog Text 67"
                        },
                        new
                        {
                            Id = 68,
                            Author = "http://author68.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1396),
                            Description = "Blog Description 68",
                            Text = "Blog Text 68"
                        },
                        new
                        {
                            Id = 69,
                            Author = "http://author69.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1410),
                            Description = "Blog Description 69",
                            Text = "Blog Text 69"
                        },
                        new
                        {
                            Id = 70,
                            Author = "http://author70.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1425),
                            Description = "Blog Description 70",
                            Text = "Blog Text 70"
                        },
                        new
                        {
                            Id = 71,
                            Author = "http://author71.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1475),
                            Description = "Blog Description 71",
                            Text = "Blog Text 71"
                        },
                        new
                        {
                            Id = 72,
                            Author = "http://author72.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1494),
                            Description = "Blog Description 72",
                            Text = "Blog Text 72"
                        },
                        new
                        {
                            Id = 73,
                            Author = "http://author73.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1508),
                            Description = "Blog Description 73",
                            Text = "Blog Text 73"
                        },
                        new
                        {
                            Id = 74,
                            Author = "http://author74.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1522),
                            Description = "Blog Description 74",
                            Text = "Blog Text 74"
                        },
                        new
                        {
                            Id = 75,
                            Author = "http://author75.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1537),
                            Description = "Blog Description 75",
                            Text = "Blog Text 75"
                        },
                        new
                        {
                            Id = 76,
                            Author = "http://author76.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1551),
                            Description = "Blog Description 76",
                            Text = "Blog Text 76"
                        },
                        new
                        {
                            Id = 77,
                            Author = "http://author77.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1565),
                            Description = "Blog Description 77",
                            Text = "Blog Text 77"
                        },
                        new
                        {
                            Id = 78,
                            Author = "http://author78.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1580),
                            Description = "Blog Description 78",
                            Text = "Blog Text 78"
                        },
                        new
                        {
                            Id = 79,
                            Author = "http://author79.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1594),
                            Description = "Blog Description 79",
                            Text = "Blog Text 79"
                        },
                        new
                        {
                            Id = 80,
                            Author = "http://author80.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1608),
                            Description = "Blog Description 80",
                            Text = "Blog Text 80"
                        },
                        new
                        {
                            Id = 81,
                            Author = "http://author81.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1623),
                            Description = "Blog Description 81",
                            Text = "Blog Text 81"
                        },
                        new
                        {
                            Id = 82,
                            Author = "http://author82.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1637),
                            Description = "Blog Description 82",
                            Text = "Blog Text 82"
                        },
                        new
                        {
                            Id = 83,
                            Author = "http://author83.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1651),
                            Description = "Blog Description 83",
                            Text = "Blog Text 83"
                        },
                        new
                        {
                            Id = 84,
                            Author = "http://author84.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1665),
                            Description = "Blog Description 84",
                            Text = "Blog Text 84"
                        },
                        new
                        {
                            Id = 85,
                            Author = "http://author85.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1679),
                            Description = "Blog Description 85",
                            Text = "Blog Text 85"
                        },
                        new
                        {
                            Id = 86,
                            Author = "http://author86.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1694),
                            Description = "Blog Description 86",
                            Text = "Blog Text 86"
                        },
                        new
                        {
                            Id = 87,
                            Author = "http://author87.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1706),
                            Description = "Blog Description 87",
                            Text = "Blog Text 87"
                        },
                        new
                        {
                            Id = 88,
                            Author = "http://author88.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1721),
                            Description = "Blog Description 88",
                            Text = "Blog Text 88"
                        },
                        new
                        {
                            Id = 89,
                            Author = "http://author89.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1769),
                            Description = "Blog Description 89",
                            Text = "Blog Text 89"
                        },
                        new
                        {
                            Id = 90,
                            Author = "http://author90.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1788),
                            Description = "Blog Description 90",
                            Text = "Blog Text 90"
                        },
                        new
                        {
                            Id = 91,
                            Author = "http://author91.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1802),
                            Description = "Blog Description 91",
                            Text = "Blog Text 91"
                        },
                        new
                        {
                            Id = 92,
                            Author = "http://author92.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1817),
                            Description = "Blog Description 92",
                            Text = "Blog Text 92"
                        },
                        new
                        {
                            Id = 93,
                            Author = "http://author93.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1831),
                            Description = "Blog Description 93",
                            Text = "Blog Text 93"
                        },
                        new
                        {
                            Id = 94,
                            Author = "http://author94.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1845),
                            Description = "Blog Description 94",
                            Text = "Blog Text 94"
                        },
                        new
                        {
                            Id = 95,
                            Author = "http://author95.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1859),
                            Description = "Blog Description 95",
                            Text = "Blog Text 95"
                        },
                        new
                        {
                            Id = 96,
                            Author = "http://author96.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1873),
                            Description = "Blog Description 96",
                            Text = "Blog Text 96"
                        },
                        new
                        {
                            Id = 97,
                            Author = "http://author97.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1886),
                            Description = "Blog Description 97",
                            Text = "Blog Text 97"
                        },
                        new
                        {
                            Id = 98,
                            Author = "http://author98.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1901),
                            Description = "Blog Description 98",
                            Text = "Blog Text 98"
                        },
                        new
                        {
                            Id = 99,
                            Author = "http://author99.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1918),
                            Description = "Blog Description 99",
                            Text = "Blog Text 99"
                        },
                        new
                        {
                            Id = 100,
                            Author = "http://author100.com",
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1933),
                            Description = "Blog Description 100",
                            Text = "Blog Text 100"
                        });
                });

            modelBuilder.Entity("Vega.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ExpenseGroupId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Vega.Models.ExpenseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Expense_groups");
                });

            modelBuilder.Entity("Vega.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IncomeGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncomeGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("Vega.Models.IncomeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Income_groups");
                });

            modelBuilder.Entity("Vega.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reminder_day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Reminder_dayEnum")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Vega.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AccountTypeEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = "Regular",
                            AccountTypeEnum = 0,
                            Created_at = new DateTime(2024, 1, 18, 15, 1, 52, 251, DateTimeKind.Local).AddTicks(1963),
                            Email = "admin@gmail.com",
                            Password = "06032004",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Vega.Models.Expense", b =>
                {
                    b.HasOne("Vega.Models.ExpenseGroup", "ExpenseGroup")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vega.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vega.Models.Income", b =>
                {
                    b.HasOne("Vega.Models.IncomeGroup", "IncomeGroup")
                        .WithMany("Incomes")
                        .HasForeignKey("IncomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vega.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vega.Models.ExpenseGroup", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Vega.Models.IncomeGroup", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("Vega.Models.User", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
