// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240207140842_NewMigrations")]
    partial class NewMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "http://author1.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6297),
                            Description = "Blog Description 1",
                            Text = "Blog Text 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Author = "http://author2.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6350),
                            Description = "Blog Description 2",
                            Text = "Blog Text 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Author = "http://author3.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6367),
                            Description = "Blog Description 3",
                            Text = "Blog Text 3",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Author = "http://author4.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6383),
                            Description = "Blog Description 4",
                            Text = "Blog Text 4",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Author = "http://author5.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6398),
                            Description = "Blog Description 5",
                            Text = "Blog Text 5",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Author = "http://author6.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6417),
                            Description = "Blog Description 6",
                            Text = "Blog Text 6",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            Author = "http://author7.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6432),
                            Description = "Blog Description 7",
                            Text = "Blog Text 7",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Author = "http://author8.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6446),
                            Description = "Blog Description 8",
                            Text = "Blog Text 8",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Author = "http://author9.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6517),
                            Description = "Blog Description 9",
                            Text = "Blog Text 9",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Author = "http://author10.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6536),
                            Description = "Blog Description 10",
                            Text = "Blog Text 10",
                            UserId = 1
                        },
                        new
                        {
                            Id = 11,
                            Author = "http://author11.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6556),
                            Description = "Blog Description 11",
                            Text = "Blog Text 11",
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Author = "http://author12.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6571),
                            Description = "Blog Description 12",
                            Text = "Blog Text 12",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Author = "http://author13.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6585),
                            Description = "Blog Description 13",
                            Text = "Blog Text 13",
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Author = "http://author14.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6600),
                            Description = "Blog Description 14",
                            Text = "Blog Text 14",
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Author = "http://author15.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6614),
                            Description = "Blog Description 15",
                            Text = "Blog Text 15",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Author = "http://author16.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6629),
                            Description = "Blog Description 16",
                            Text = "Blog Text 16",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            Author = "http://author17.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6644),
                            Description = "Blog Description 17",
                            Text = "Blog Text 17",
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            Author = "http://author18.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6661),
                            Description = "Blog Description 18",
                            Text = "Blog Text 18",
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Author = "http://author19.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6676),
                            Description = "Blog Description 19",
                            Text = "Blog Text 19",
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Author = "http://author20.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6690),
                            Description = "Blog Description 20",
                            Text = "Blog Text 20",
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Author = "http://author21.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6705),
                            Description = "Blog Description 21",
                            Text = "Blog Text 21",
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Author = "http://author22.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6720),
                            Description = "Blog Description 22",
                            Text = "Blog Text 22",
                            UserId = 1
                        },
                        new
                        {
                            Id = 23,
                            Author = "http://author23.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6735),
                            Description = "Blog Description 23",
                            Text = "Blog Text 23",
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Author = "http://author24.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6750),
                            Description = "Blog Description 24",
                            Text = "Blog Text 24",
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            Author = "http://author25.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6911),
                            Description = "Blog Description 25",
                            Text = "Blog Text 25",
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Author = "http://author26.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6930),
                            Description = "Blog Description 26",
                            Text = "Blog Text 26",
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            Author = "http://author27.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6945),
                            Description = "Blog Description 27",
                            Text = "Blog Text 27",
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Author = "http://author28.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6960),
                            Description = "Blog Description 28",
                            Text = "Blog Text 28",
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            Author = "http://author29.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6974),
                            Description = "Blog Description 29",
                            Text = "Blog Text 29",
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            Author = "http://author30.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(6989),
                            Description = "Blog Description 30",
                            Text = "Blog Text 30",
                            UserId = 1
                        },
                        new
                        {
                            Id = 31,
                            Author = "http://author31.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7003),
                            Description = "Blog Description 31",
                            Text = "Blog Text 31",
                            UserId = 1
                        },
                        new
                        {
                            Id = 32,
                            Author = "http://author32.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7017),
                            Description = "Blog Description 32",
                            Text = "Blog Text 32",
                            UserId = 1
                        },
                        new
                        {
                            Id = 33,
                            Author = "http://author33.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7032),
                            Description = "Blog Description 33",
                            Text = "Blog Text 33",
                            UserId = 1
                        },
                        new
                        {
                            Id = 34,
                            Author = "http://author34.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7048),
                            Description = "Blog Description 34",
                            Text = "Blog Text 34",
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            Author = "http://author35.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7063),
                            Description = "Blog Description 35",
                            Text = "Blog Text 35",
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Author = "http://author36.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7078),
                            Description = "Blog Description 36",
                            Text = "Blog Text 36",
                            UserId = 1
                        },
                        new
                        {
                            Id = 37,
                            Author = "http://author37.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7093),
                            Description = "Blog Description 37",
                            Text = "Blog Text 37",
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            Author = "http://author38.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7107),
                            Description = "Blog Description 38",
                            Text = "Blog Text 38",
                            UserId = 1
                        },
                        new
                        {
                            Id = 39,
                            Author = "http://author39.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7121),
                            Description = "Blog Description 39",
                            Text = "Blog Text 39",
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            Author = "http://author40.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7136),
                            Description = "Blog Description 40",
                            Text = "Blog Text 40",
                            UserId = 1
                        },
                        new
                        {
                            Id = 41,
                            Author = "http://author41.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7196),
                            Description = "Blog Description 41",
                            Text = "Blog Text 41",
                            UserId = 1
                        },
                        new
                        {
                            Id = 42,
                            Author = "http://author42.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7216),
                            Description = "Blog Description 42",
                            Text = "Blog Text 42",
                            UserId = 1
                        },
                        new
                        {
                            Id = 43,
                            Author = "http://author43.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7231),
                            Description = "Blog Description 43",
                            Text = "Blog Text 43",
                            UserId = 1
                        },
                        new
                        {
                            Id = 44,
                            Author = "http://author44.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7246),
                            Description = "Blog Description 44",
                            Text = "Blog Text 44",
                            UserId = 1
                        },
                        new
                        {
                            Id = 45,
                            Author = "http://author45.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7260),
                            Description = "Blog Description 45",
                            Text = "Blog Text 45",
                            UserId = 1
                        },
                        new
                        {
                            Id = 46,
                            Author = "http://author46.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7275),
                            Description = "Blog Description 46",
                            Text = "Blog Text 46",
                            UserId = 1
                        },
                        new
                        {
                            Id = 47,
                            Author = "http://author47.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7290),
                            Description = "Blog Description 47",
                            Text = "Blog Text 47",
                            UserId = 1
                        },
                        new
                        {
                            Id = 48,
                            Author = "http://author48.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7305),
                            Description = "Blog Description 48",
                            Text = "Blog Text 48",
                            UserId = 1
                        },
                        new
                        {
                            Id = 49,
                            Author = "http://author49.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7319),
                            Description = "Blog Description 49",
                            Text = "Blog Text 49",
                            UserId = 1
                        },
                        new
                        {
                            Id = 50,
                            Author = "http://author50.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7334),
                            Description = "Blog Description 50",
                            Text = "Blog Text 50",
                            UserId = 1
                        },
                        new
                        {
                            Id = 51,
                            Author = "http://author51.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7348),
                            Description = "Blog Description 51",
                            Text = "Blog Text 51",
                            UserId = 1
                        },
                        new
                        {
                            Id = 52,
                            Author = "http://author52.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7364),
                            Description = "Blog Description 52",
                            Text = "Blog Text 52",
                            UserId = 1
                        },
                        new
                        {
                            Id = 53,
                            Author = "http://author53.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7378),
                            Description = "Blog Description 53",
                            Text = "Blog Text 53",
                            UserId = 1
                        },
                        new
                        {
                            Id = 54,
                            Author = "http://author54.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7393),
                            Description = "Blog Description 54",
                            Text = "Blog Text 54",
                            UserId = 1
                        },
                        new
                        {
                            Id = 55,
                            Author = "http://author55.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7407),
                            Description = "Blog Description 55",
                            Text = "Blog Text 55",
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            Author = "http://author56.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7422),
                            Description = "Blog Description 56",
                            Text = "Blog Text 56",
                            UserId = 1
                        },
                        new
                        {
                            Id = 57,
                            Author = "http://author57.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7437),
                            Description = "Blog Description 57",
                            Text = "Blog Text 57",
                            UserId = 1
                        },
                        new
                        {
                            Id = 58,
                            Author = "http://author58.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7451),
                            Description = "Blog Description 58",
                            Text = "Blog Text 58",
                            UserId = 1
                        },
                        new
                        {
                            Id = 59,
                            Author = "http://author59.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7502),
                            Description = "Blog Description 59",
                            Text = "Blog Text 59",
                            UserId = 1
                        },
                        new
                        {
                            Id = 60,
                            Author = "http://author60.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7519),
                            Description = "Blog Description 60",
                            Text = "Blog Text 60",
                            UserId = 1
                        },
                        new
                        {
                            Id = 61,
                            Author = "http://author61.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7534),
                            Description = "Blog Description 61",
                            Text = "Blog Text 61",
                            UserId = 1
                        },
                        new
                        {
                            Id = 62,
                            Author = "http://author62.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7548),
                            Description = "Blog Description 62",
                            Text = "Blog Text 62",
                            UserId = 1
                        },
                        new
                        {
                            Id = 63,
                            Author = "http://author63.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7563),
                            Description = "Blog Description 63",
                            Text = "Blog Text 63",
                            UserId = 1
                        },
                        new
                        {
                            Id = 64,
                            Author = "http://author64.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7577),
                            Description = "Blog Description 64",
                            Text = "Blog Text 64",
                            UserId = 1
                        },
                        new
                        {
                            Id = 65,
                            Author = "http://author65.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7593),
                            Description = "Blog Description 65",
                            Text = "Blog Text 65",
                            UserId = 1
                        },
                        new
                        {
                            Id = 66,
                            Author = "http://author66.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7610),
                            Description = "Blog Description 66",
                            Text = "Blog Text 66",
                            UserId = 1
                        },
                        new
                        {
                            Id = 67,
                            Author = "http://author67.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7626),
                            Description = "Blog Description 67",
                            Text = "Blog Text 67",
                            UserId = 1
                        },
                        new
                        {
                            Id = 68,
                            Author = "http://author68.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7641),
                            Description = "Blog Description 68",
                            Text = "Blog Text 68",
                            UserId = 1
                        },
                        new
                        {
                            Id = 69,
                            Author = "http://author69.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7656),
                            Description = "Blog Description 69",
                            Text = "Blog Text 69",
                            UserId = 1
                        },
                        new
                        {
                            Id = 70,
                            Author = "http://author70.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7671),
                            Description = "Blog Description 70",
                            Text = "Blog Text 70",
                            UserId = 1
                        },
                        new
                        {
                            Id = 71,
                            Author = "http://author71.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7685),
                            Description = "Blog Description 71",
                            Text = "Blog Text 71",
                            UserId = 1
                        },
                        new
                        {
                            Id = 72,
                            Author = "http://author72.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7700),
                            Description = "Blog Description 72",
                            Text = "Blog Text 72",
                            UserId = 1
                        },
                        new
                        {
                            Id = 73,
                            Author = "http://author73.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7715),
                            Description = "Blog Description 73",
                            Text = "Blog Text 73",
                            UserId = 1
                        },
                        new
                        {
                            Id = 74,
                            Author = "http://author74.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7730),
                            Description = "Blog Description 74",
                            Text = "Blog Text 74",
                            UserId = 1
                        },
                        new
                        {
                            Id = 75,
                            Author = "http://author75.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7780),
                            Description = "Blog Description 75",
                            Text = "Blog Text 75",
                            UserId = 1
                        },
                        new
                        {
                            Id = 76,
                            Author = "http://author76.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7796),
                            Description = "Blog Description 76",
                            Text = "Blog Text 76",
                            UserId = 1
                        },
                        new
                        {
                            Id = 77,
                            Author = "http://author77.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7811),
                            Description = "Blog Description 77",
                            Text = "Blog Text 77",
                            UserId = 1
                        },
                        new
                        {
                            Id = 78,
                            Author = "http://author78.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7826),
                            Description = "Blog Description 78",
                            Text = "Blog Text 78",
                            UserId = 1
                        },
                        new
                        {
                            Id = 79,
                            Author = "http://author79.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7841),
                            Description = "Blog Description 79",
                            Text = "Blog Text 79",
                            UserId = 1
                        },
                        new
                        {
                            Id = 80,
                            Author = "http://author80.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7855),
                            Description = "Blog Description 80",
                            Text = "Blog Text 80",
                            UserId = 1
                        },
                        new
                        {
                            Id = 81,
                            Author = "http://author81.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7869),
                            Description = "Blog Description 81",
                            Text = "Blog Text 81",
                            UserId = 1
                        },
                        new
                        {
                            Id = 82,
                            Author = "http://author82.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7884),
                            Description = "Blog Description 82",
                            Text = "Blog Text 82",
                            UserId = 1
                        },
                        new
                        {
                            Id = 83,
                            Author = "http://author83.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7898),
                            Description = "Blog Description 83",
                            Text = "Blog Text 83",
                            UserId = 1
                        },
                        new
                        {
                            Id = 84,
                            Author = "http://author84.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7913),
                            Description = "Blog Description 84",
                            Text = "Blog Text 84",
                            UserId = 1
                        },
                        new
                        {
                            Id = 85,
                            Author = "http://author85.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7928),
                            Description = "Blog Description 85",
                            Text = "Blog Text 85",
                            UserId = 1
                        },
                        new
                        {
                            Id = 86,
                            Author = "http://author86.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7942),
                            Description = "Blog Description 86",
                            Text = "Blog Text 86",
                            UserId = 1
                        },
                        new
                        {
                            Id = 87,
                            Author = "http://author87.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7957),
                            Description = "Blog Description 87",
                            Text = "Blog Text 87",
                            UserId = 1
                        },
                        new
                        {
                            Id = 88,
                            Author = "http://author88.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7972),
                            Description = "Blog Description 88",
                            Text = "Blog Text 88",
                            UserId = 1
                        },
                        new
                        {
                            Id = 89,
                            Author = "http://author89.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(7987),
                            Description = "Blog Description 89",
                            Text = "Blog Text 89",
                            UserId = 1
                        },
                        new
                        {
                            Id = 90,
                            Author = "http://author90.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8001),
                            Description = "Blog Description 90",
                            Text = "Blog Text 90",
                            UserId = 1
                        },
                        new
                        {
                            Id = 91,
                            Author = "http://author91.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8017),
                            Description = "Blog Description 91",
                            Text = "Blog Text 91",
                            UserId = 1
                        },
                        new
                        {
                            Id = 92,
                            Author = "http://author92.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8085),
                            Description = "Blog Description 92",
                            Text = "Blog Text 92",
                            UserId = 1
                        },
                        new
                        {
                            Id = 93,
                            Author = "http://author93.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8102),
                            Description = "Blog Description 93",
                            Text = "Blog Text 93",
                            UserId = 1
                        },
                        new
                        {
                            Id = 94,
                            Author = "http://author94.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8117),
                            Description = "Blog Description 94",
                            Text = "Blog Text 94",
                            UserId = 1
                        },
                        new
                        {
                            Id = 95,
                            Author = "http://author95.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8132),
                            Description = "Blog Description 95",
                            Text = "Blog Text 95",
                            UserId = 1
                        },
                        new
                        {
                            Id = 96,
                            Author = "http://author96.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8146),
                            Description = "Blog Description 96",
                            Text = "Blog Text 96",
                            UserId = 1
                        },
                        new
                        {
                            Id = 97,
                            Author = "http://author97.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8161),
                            Description = "Blog Description 97",
                            Text = "Blog Text 97",
                            UserId = 1
                        },
                        new
                        {
                            Id = 98,
                            Author = "http://author98.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8175),
                            Description = "Blog Description 98",
                            Text = "Blog Text 98",
                            UserId = 1
                        },
                        new
                        {
                            Id = 99,
                            Author = "http://author99.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8190),
                            Description = "Blog Description 99",
                            Text = "Blog Text 99",
                            UserId = 1
                        },
                        new
                        {
                            Id = 100,
                            Author = "http://author100.com",
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(8204),
                            Description = "Blog Description 100",
                            Text = "Blog Text 100",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ExpenseGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Domain.Models.ExpenseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseGroups");
                });

            modelBuilder.Entity("Domain.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IncomeGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncomeGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("Domain.Models.IncomeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IncomeGroups");
                });

            modelBuilder.Entity("Domain.Models.Reminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReminderDay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReminderDayEnum")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AccountTypeEnum")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = "Administrator",
                            AccountTypeEnum = 1,
                            CreatedAt = new DateTime(2024, 2, 7, 15, 8, 41, 391, DateTimeKind.Local).AddTicks(5363),
                            Email = "admin@gmail.com",
                            IsVerified = false,
                            Password = "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
                            Username = "Administrator"
                        });
                });

            modelBuilder.Entity("Domain.Models.Blog", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Expense", b =>
                {
                    b.HasOne("Domain.Models.ExpenseGroup", "ExpenseGroup")
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.ExpenseGroup", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("ExpenseGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Income", b =>
                {
                    b.HasOne("Domain.Models.IncomeGroup", "IncomeGroup")
                        .WithMany("Incomes")
                        .HasForeignKey("IncomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.IncomeGroup", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("IncomeGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.ExpenseGroup", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Domain.Models.IncomeGroup", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("ExpenseGroups");

                    b.Navigation("Expenses");

                    b.Navigation("IncomeGroups");

                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
